/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Issac Ghazanfar (https://sketchfab.com/sheshhh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-laptop-7ceb46a1425b475fa7f6bf192e01ed74
Title: MacBook Laptop
*/

import React, { useRef } from 'react'
import PropTypes from 'prop-types'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'

const Laptop = (props) => {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/laptop.glb')
    const txt = useVideoTexture(props.texture)

    useGSAP(() => {
        gsap.from(group.current.rotation,{
            y: Math.PI / 2,
            duration: 1,
            ease: 'power3.out',
        } )
    }, [txt])

    return (
        <group ref={group} {...props} dispose={null}>
            <group scale={0.1} position={[0, 1, 0]}>
                <group
                    position={[-0.223, -5.477, 1.396]}
                    rotation={[Math.PI, 0, 0]}
                    scale={[9.059, 7.172, 9.059]}>
                    <group
                        position={[0.001, -1.421, 1.468]}
                        rotation={[1.386, 0, 0]}
                        scale={[11.038, 11.143, 13.86]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_Material002_0.geometry}
                            material={materials['Material.002']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_Material003_0.geometry}
                            material={materials['Material.003']}
                        >
                            <meshBasicMaterial map={txt} />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_Material004_0.geometry}
                            material={materials['Material.004']}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube001_Material002_0.geometry}
                        material={materials['Material.002']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002_Material002_0.geometry}
                        material={materials['Material.002']}
                        position={[-0.01, -0.047, -0.739]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[1.035, 0.972, 0.968]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Keyboard_Material001_0.geometry}
                        material={materials['Material.001']}
                        position={[0.024, -0.032, 0.48]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.976, 0.976, 0.978]}
                    />
                </group>
            </group>
        </group>
    )
}

Laptop.propTypes = {
    texture: PropTypes.string.isRequired,
}
useGLTF.preload('/models/laptop.glb')

export default Laptop
